name: Deploy Spring Boot to Pinggy
on: 
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      
      - name: Verify project structure
        run: |
          echo "🔍 Checking project structure..."
          ls -la
          echo "📁 Looking for pom.xml files:"
          find . -name "pom.xml" -type f
          
          if [ ! -f "pom.xml" ]; then
            echo "❌ No pom.xml found in root directory"
            echo "Please ensure your Spring Boot project is in the repository root"
            echo "Or modify the action to cd into the correct directory"
            exit 1
          fi
          
          echo "✅ pom.xml found, checking if it's a Spring Boot project..."
          if grep -q "spring-boot" pom.xml; then
            echo "✅ Spring Boot dependencies found"
          else
            echo "⚠️  Warning: No Spring Boot dependencies detected in pom.xml"
          fi
      
      - name: Build with Maven
        run: |
          echo "🏗️ Building Spring Boot application..."
          mvn clean package -DskipTests -B -V
          
          echo "📦 Checking build output..."
          ls -la target/
          
          if ls target/*.jar 1> /dev/null 2>&1; then
            echo "✅ JAR file built successfully:"
            ls -la target/*.jar
          else
            echo "❌ No JAR file found in target directory"
            exit 1
          fi
      
      - name: Start Spring Boot application
        run: |
          echo "🚀 Starting Spring Boot application..."
          
          # Find the JAR file (exclude original and plain JARs)
          JAR_FILE=$(find target -name "*.jar" -not -name "*-original.jar" -not -name "*-plain.jar" | head -1)
          
          if [ -z "$JAR_FILE" ]; then
            echo "❌ No executable JAR found"
            exit 1
          fi
          
          echo "📦 Starting JAR: $JAR_FILE"
          
          # Start the application in background
          nohup java -jar "$JAR_FILE" > app.log 2>&1 &
          APP_PID=$!
          echo "🆔 Application PID: $APP_PID"
          
          # Wait for application to start
          echo "⏳ Waiting for application to start..."
          for i in {1..60}; do
            if curl -s http://localhost:8080/actuator/health > /dev/null 2>&1; then
              echo "✅ Application health check passed"
              break
            elif curl -s http://localhost:8080 > /dev/null 2>&1; then
              echo "✅ Application is responding"
              break
            else
              if [ $i -eq 60 ]; then
                echo "❌ Application failed to start within 60 seconds"
                echo "📋 Application logs:"
                cat app.log
                exit 1
              fi
              echo "⏳ Waiting... ($i/60)"
              sleep 1
            fi
          done
      
      - name: Test local endpoints
        run: |
          echo "🧪 Testing local endpoints..."
          
          # Test root endpoint
          echo "Testing http://localhost:8080/"
          curl -v http://localhost:8080/ || echo "Root endpoint not available"
          
          # Test health endpoint
          echo "Testing http://localhost:8080/actuator/health"
          curl -v http://localhost:8080/actuator/health || echo "Health endpoint not available"
          
          # Test any custom /api endpoint
          echo "Testing http://localhost:8080/api"
          curl -v http://localhost:8080/api || echo "API endpoint not available"
      
      - name: Create Pinggy tunnel
        run: |
          echo "🌐 Creating Pinggy tunnel..."
          ssh -p 443 \
              -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=30 \
              -R0:localhost:8080 a.pinggy.io &
          
          sleep 5
          echo "✅ Tunnel created! Check logs above for public URL"
      
      - name: Keep workflow alive and monitor
        run: |
          echo "🕐 Keeping workflow alive for 5 minutes..."
          echo "🔗 Your Spring Boot app should be accessible via the Pinggy URL above"
          
          for i in {1..10}; do
            echo "⏳ $((i*30)) seconds elapsed..."
            
            # Show recent app logs
            if [ -f app.log ]; then
              echo "📋 Recent application logs:"
              tail -10 app.log
            fi
            
            # Check if app is still running
            if curl -s http://localhost:8080/actuator/health > /dev/null 2>&1; then
              echo "✅ App still healthy"
            else
              echo "⚠️ App health check failed"
            fi
            
            sleep 30
          done
          
          echo "✅ Workflow completed"
