name: Start Minikube in Codespace and making port public

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  start-minikube:
    runs-on: ubuntu-latest
    
    steps:
    - name: Authenticate with GitHub CLI
      run: |
        echo "${{ secrets.GH_GITHUB_TOKEN }}" | gh auth login --with-token
    
    - name: Get or Create Codespace
      run: |
        # Get existing codespace or create new one
        CODESPACE_NAME=$(gh codespace list --json name --jq '.[0].name // empty')
        
        if [ -z "$CODESPACE_NAME" ]; then
          echo "Creating new codespace..."
          gh codespace create --repo ${{ github.repository }}
          sleep 30
          CODESPACE_NAME=$(gh codespace list --json name --jq '.[0].name')
        fi
        
        echo "CODESPACE_NAME=$CODESPACE_NAME" >> $GITHUB_ENV
        echo "Using codespace: $CODESPACE_NAME"
    
    - name: Start Minikube
      run: |
        gh codespace ssh --codespace congenial-funicular-5gg6p454rxxxcpxrg -- bash -c "
          echo 'Starting minikube...'
          minikube start --driver=docker
          echo 'Minikube status:'
          minikube status
          # Make sure your hello-app-service is actually deployed
          kubectl get services
          echo 'Starting port-forward for hello-app-service...'
          nohup kubectl port-forward service/hello-app-service 8080:80 --address=0.0.0.0 > /dev/null 2>&1 &
          echo 'sleeping 10sec'
          sleep 10
          echo 'Making port 8080 public...'
          echo "${{ secrets.GH_GITHUB_TOKEN }}" | gh auth login --with-token
          gh codespace ports visibility 8080:public
        "
        echo 'Sleeping for 5 minutes to keep everything running...'
        sleep 300